import type { ArtistDecisionPayload } from "@/components/decision-center/types";

type TrackAnalysisContextPanelProps = {
  payload: ArtistDecisionPayload;
};

type ContextItem = {
  label: string;
  value: string;
};

function hasText(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function formatNumber(value: unknown, fractionDigits = 0): string | null {
  const numberValue = Number(value);

  if (!Number.isFinite(numberValue)) {
    return null;
  }

  return numberValue.toFixed(fractionDigits);
}

function formatDuration(durationSec: unknown): string | null {
  const seconds = Number(durationSec);

  if (!Number.isFinite(seconds) || seconds <= 0) {
    return null;
  }

  const roundedSeconds = Math.round(seconds);
  const minutes = Math.floor(roundedSeconds / 60);
  const remainingSeconds = roundedSeconds % 60;

  return `${minutes}:${String(remainingSeconds).padStart(2, "0")}`;
}

function buildContextItems(payload: ArtistDecisionPayload): ContextItem[] {
  const track = payload.track;
  const declaredBpm = formatNumber(track.declared_bpm ?? track.bpm, 0) || null;

  return [
    {
      label: "Main genre",
      value: hasText(track.main_genre) ? track.main_genre : "Not provided",
    },
    {
      label: "Subgenre",
      value: hasText(track.subgenre) ? track.subgenre : "Not provided",
    },
    {
      label: "Declared BPM",
      value: declaredBpm ? `${declaredBpm} BPM` : "Not provided",
    },
    {
      label: "Declared key",
      value: hasText(track.declared_key ?? track.key)
        ? String(track.declared_key ?? track.key)
        : "Not provided",
    },
    {
      label: "Version",
      value: hasText(track.version) ? track.version : "Not provided",
    },
    {
      label: "Duration",
      value: formatDuration(track.duration_sec) || "Not available",
    },
  ];
}

export function TrackAnalysisContextPanel({
  payload,
}: TrackAnalysisContextPanelProps) {
  const items = buildContextItems(payload);

  return (
    <section className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
      <div>
        <p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-300/80">
          Artist Input
        </p>

        <h2 className="mt-2 text-lg font-semibold text-white">
          Upload metadata
        </h2>

        <p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">
          These are the track details provided before analysis. They frame the
          feedback but are not generated by the engine.
        </p>
      </div>

      <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">
        {items.map((item) => (
          <div
            key={item.label}
            className="rounded-2xl border border-white/10 bg-black/20 p-4"
          >
            <p className="text-xs uppercase tracking-[0.18em] text-zinc-500">
              {item.label}
            </p>

            <p className="mt-2 text-sm font-semibold text-white">
              {item.value}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}
